[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-run --chip STM32F401RETx"

rustflags = [
    "-C", "link-arg=--nmagic",
    "-C", "link-arg=-Tlink.x",
    "-C", "link-arg=-Tdefmt.x",
    "-C", "linker=flip-link"
]

[build]
target = "thumbv7em-none-eabihf"

[env]
DEFMT_LOG = "trace"
